HospitalManagementSystem/Models/Compte.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public Compte()
        {
        }

        public virtual Configuration Configuration { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}

HospitalManagementSystem/Controllers/CompteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalManagementSystem.Models;
using System.Text;
using System.IO;

namespace HospitalManagementSystem.Controllers
{
    [Authorize]
    public class CompteController : Controller
    {
        private Clinique_dbEntities db = new Clinique_dbEntities();

        // GET: Compte
        public async Task<ActionResult> Index()
        {
            var comptes = db.Comptes.Include(c => c.Configuration).Include(c => c.Personnel);
            return View(await comptes.ToListAsync());
        }

        

     public ActionResult GetAll()
        {
            var comptes = db.Comptes.Include(c => c.Configuration).Include(c => c.Personnel);
            return PartialView( comptes.ToList());
        }

        // GET: Compte/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compte compte = await db.Comptes.FindAsync(id);
            if (compte == null)
            {
                return HttpNotFound();
            }
            return View(compte);
        }

        // GET: Compte/Create
        public ActionResult Create()
        {
            ViewBag.IdRole = new SelectList(db.Configurations.Where(x => x.Libelle.Equals("Administrateur") || x.Libelle.Equals("Simple utilisateur")), "IdConfiguration", "Libelle");
            ViewBag.CodePersonnel = new SelectList(db.Personnels, "Code", "NomComplet");
            return View();
        }


        public ActionResult Profil()
        {

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> SaveProfil(HttpPostedFileBase imgfile, string code)
        {

            if (imgfile != null && imgfile.ContentLength > 0)
            {
                Personnel personnel = await db.Personnels.FindAsync(code);
                string imgname = Path.GetFileName(imgfile.FileName);
                string imgext = Path.GetExtension(imgname);
                imgname = personnel.Code + imgext;
                string imgpath = Path.Combine(Server.MapPath("~/Img"), imgname);
                imgfile.SaveAs(imgpath);
                string p = imgpath.Substring(15);
               // User u = await db.Users.FindAsync(account.User.Matricule);
                personnel.Photo = imgname;
                db.Entry(personnel).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }


            return View("Profil");
        }


        // POST: Compte/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Login,MotDePasse,Statut,CodePersonnel,IdRole")] Compte compte)
        {
            if (ModelState.IsValid)
            {
                db.Comptes.Add(compte);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IdRole = new SelectList(db.Configurations.Where(x=>x.Libelle.Equals("Administrateur") || x.Libelle.Equals("Simple utilisateur")), "IdConfiguration", "Libelle", compte.IdRole);
            ViewBag.CodePersonnel = new SelectList(db.Personnels, "Code", "NomComplet", compte.CodePersonnel);
            return View(compte);
        }

        // GET: Compte/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compte compte = await db.Comptes.FindAsync(id);
            if (compte == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdRole = new SelectList(db.Configurations.Where(x => x.Libelle.Equals("Administrateur") || x.Libelle.Equals("Simple utilisateur")), "IdConfiguration", "Libelle", compte.IdRole);
            ViewBag.CodePersonnel = new SelectList(db.Personnels, "Code", "NomComplet", compte.CodePersonnel);
            return View(compte);
        }

        // POST: Compte/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Login,MotDePasse,Statut,CodePersonnel,IdRole")] Compte compte)
        {
            if (ModelState.IsValid)
            {

                compte.MotDePasse = CreateMD5(compte.MotDePasse);


                db.Entry(compte).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdRole = new SelectList(db.Configurations.Where(x => x.Libelle.Equals("Administrateur") || x.Libelle.Equals("Simple utilisateur")), "IdConfiguration", "Libelle", compte.IdRole);
            ViewBag.CodePersonnel = new SelectList(db.Personnels, "Code", "NomComplet", compte.CodePersonnel);
            return View(compte);
        }


        public static string CreateMD5(string input)
        {
            // Use input string to calculate MD5 hash
            using (System.Security.Cryptography.MD5 md5 = System.Security.Cryptography.MD5.Create())
            {
                byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(input);
                byte[] hashBytes = md5.ComputeHash(inputBytes);

                // Convert the byte array to hexadecimal string
                StringBuilder sb = new StringBuilder();
                for (int i = 0; i < hashBytes.Length; i++)
                {
                    sb.Append(hashBytes[i].ToString("X2"));
                }
                return sb.ToString();
            }
        }

        // GET: Compte/Delete/5
        public async Task<ActionResult> ActiverDesactiver(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compte compte = await db.Comptes.FindAsync(id);
            if (compte == null)
            {
                return HttpNotFound();
            }
            return View(compte);
        }

        // POST: Compte/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> ActiverDesactiverConfirmed(int id)
        {
            Compte compte = await db.Comptes.FindAsync(id);
            if (compte.Statut == 1)
            {
                compte.Statut = 0;
            }
            else
            {
                compte.Statut = 1;
            }
            db.Entry(compte).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalManagementSystem/Views/Compte/ActiverDesactiver.cshtml
@model HospitalManagementSystem.Models.Compte

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Voulez-vous vraiment désactiver ce compte ?</h3>
<div>
    <h4>Désactivation de compte</h4>
    <hr />

    @{ int Id = Model.Id; }
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotDePasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotDePasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>

    @*@using (Html.BeginForm("ActiverDesactiverConfirmed", "Compte"))
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |

                 @Html.DisplayFor(model => model.Id)
                @Html.ActionLink("Annuler", "Index")

            </div>
        }*@
        <a href="@Url.Action("ActiverDesactiverConfirmed","Compte",new { id = Model.Id })">Validation</a>
         @Html.ActionLink("Annuler", "Index","Compte")
</div>

HospitalManagementSystem/Views/Compte/Create.cshtml
@model HospitalManagementSystem.Models.Compte

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div div class="col-md-3">

</div>
<div div class="col-md-6">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Creation de compte d'utilisateur</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MotDePasse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MotDePasse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Statut, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CodePersonnel, "CodePersonnel", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CodePersonnel", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodePersonnel, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IdRole, "IdRole", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IdRole", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdRole, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enregistrer" class="btn btn-default" />
                </div>
            </div>
        </div>
    }


    <div>
        @Html.ActionLink("Retour", "Index")
    </div>
</div>
<div div class="col-md-3">

</div>


@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

HospitalManagementSystem/Views/Compte/Details.cshtml
@model HospitalManagementSystem.Models.Compte

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Compte</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Login)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Login)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotDePasse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotDePasse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalManagementSystem/Views/Compte/Edit.cshtml
@model HospitalManagementSystem.Models.Compte

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div div class="col-md-3">

</div>

<div div class="col-md-6">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Modification de compte</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MotDePasse, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MotDePasse, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Statut, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CodePersonnel, "CodePersonnel", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CodePersonnel", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CodePersonnel, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IdRole, "IdRole", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IdRole", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdRole, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Retour", "Index")
    </div>
</div>
<div div class="col-md-3">

</div>


@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

HospitalManagementSystem/Views/Compte/GetAll.cshtml
@model IEnumerable<HospitalManagementSystem.Models.Compte>


    <table id="data-table" class="table table-striped table-bordered nowrap" width="100%">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Personnel.Nom)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Login)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Statut)
                </th>
                <th>
                    Role
                </th>

                <th>Action</th>
            </tr>
        </thead>
       

        @foreach (var item in Model)
        {
            if (item.Statut == 0)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Personnel.NomComplet)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Login)
                    </td>
                   
                    <td style="color:red">
                        Désactivé
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Configuration.Libelle)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Activer", "ActiverDesactiver", new { id = item.Id })
                        <a href="#" class="btn mb-1 btn-primary btn-xm" onclick="confirmeactiver(@item.Id)"><i>Activer</i></a>
                    </td>
                </tr>
            }
            else
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Personnel.NomComplet)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Login)
                    </td>
                  
                    <td style="color:green">
                        Activé
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Configuration.Libelle)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @*@Html.ActionLink("Désactiver", "ActiverDesactiver", new { id = item.Id })*@
                        <a href="#" class="btn mb-1 btn-primary btn-xm" onclick="confirmedesactiver(@item.Id)"><i>Désactiver</i></a>
                    </td>
                </tr>
            }

        }

    </table>

HospitalManagementSystem/Views/Compte/Index.cshtml
@model IEnumerable<HospitalManagementSystem.Models.Compte>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nouveau", "Create")
</p>

<div >
    <div col-md-2>

    </div>
    <div col-md-8 id="dataContainer">
        @{ Html.RenderAction("GetAll", "Compte");}
    </div>
    <div col-md-2>

    </div>
</div>


<input type="hidden" id="hiddenAccountId" />

<!-- Modal -->
<div class="modal fade" id="mymodalactiver">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Modal Dialog</h4>
            </div>
            <div class="modal-body" id="myModalBody">
                Voulez-vous vraiment activer le compte de ?
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Close</a>
                <a href="#" onclick="activaterAccount()" class="btn mb-1 btn-primary btn-xs ">Oui</a>
            </div>
        </div>
    </div>
</div>







<!-- Modal -->
<div class="modal fade" id="mymodaldesactiver">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Modal Dialog</h4>
            </div>
            <div class="modal-body" id="myModalBody2">
                Voulez-vous vraiment désactiver le compte de ?
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Close</a>
                <a href="#" onclick="desactivaterAccount()" class="btn mb-1 btn-primary btn-xs ">Oui</a>
            </div>
        </div>
    </div>
</div>





<script>
    //confirme définitivement la désactivation
        var desactivaterAccount = function () {

            //$("#loaderVid").show();
            var donnee = $("#hiddenAccountId").val();
            $.ajax({
                type: "POST",
                url: "/Compte/ActiverDesactiverConfirmed",
                data: { id: donnee },
                success: function () {
                   
                    $("#mymodaldesactiver").modal("hide");
                    
                    GetList();
                },

            });

         }

        //confirme définitivement l'activation
         var activaterAccount = function () {

            //$("#loaderVid").show();
            var donnee = $("#hiddenAccountId").val();
            $.ajax({
                type: "POST",
                url: "/Compte/ActiverDesactiverConfirmed",
                data: { id: donnee },
                success: function () {
                    //$("#loaderVid").hide();
                    $("#mymodalactiver").modal("hide");
                    //$("#table").ajax.reload();
                    GetList();

                },

            });

        }

            //affiche une vue dans un modal
        var showInPopup = function (url, title) {
            $.ajax({
                type: "GET",
                url: url,
                success: function (res) {
                    $("#form-modal .modal-body").html(res);
                    $("#form-modal .modal-title").html(title);
                    $("#form-modal").modal("show");

                    GetList();

                }
            })
        };

    //rafraichir la list
         function GetList() {
             $.ajax({
                    url: '@Url.Action("GetAll", "Compte")'

             }).done(function(result) {
                    $('#dataContainer').html(result);
                     //$('#table').DataTable()
                    console.log(result)
             }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                     console.log(textStatus)
                     console.log(errorThrown)
                     alert("Something Went Wrong, Try Later");
             });
        }

        //affiche le modal en appelant à confirmer l'activation
        var confirmeactiver = function (id) {
            $("#hiddenAccountId").val(id);
            $("#mymodalactiver").modal("show");


        }
        //affiche le modal en invitant à confirmer la désactivation
        var confirmedesactiver = function (id) {
            $("#hiddenAccountId").val(id);
            $("#mymodaldesactiver").modal("show");


         }

</script>

HospitalManagementSystem/Views/Compte/Profil.cshtml
@model HospitalManagementSystem.Models.Personnel

@{
    ViewBag.Title = "Profil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    string photo = Session["Photo"] as string;
    string path = "~/Img/";
}

<div class="container-fluid">
    <div class="modal fade" id="modalProfilImage">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">


                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="myModalBody">
                    @using (Html.BeginForm("SaveProfil", "Compte", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="card">
                            <div class="card-body">

                                <div class="media align-items-center mb-4">

                                    <div class="media-body">
                                        <img class="mr-3" id="profilImageModoal" width="80" height="80" alt="">
                                    </div>
                                </div>

                                <div class="row mb-5">
                                    <div class="col">
                                        <div class="card card-profile text-center">
                                            <input type="file" id="imgfile" value="Choisir une photo" name="imgfile" onchange="previewimg(event)" />
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="card card-profile text-center">

                                        </div>
                                    </div>
                                    <div class="col-12 text-center">

                                        <input type="submit" class="btn btn-danger px-5" value="Enregistrer" />
                                    </div>

                                    <input type="hidden" name="Code" value="@Session["Code"]" />
                                </div>

                            </div>
                        </div>

                    }
                </div>

            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-lg-4 col-xl-8">
            <div class="card">
                <div class="card-body">

                    <div class="row">
                        <div class="col-4">

                        </div>
                        <div class="col-4">
                            <div class="media ">

                                <div class="media-body">
                                    <img class="mr-3 img-circle" src="~/Img/NAFU120720.jpg" id="profilImage" width="80" height="80" alt="Photo de profil">
                                    <h3 class="mb-0">
                                        @*@{
                                            if (Session["NomCompte"] != null)
                                            {
                                                <b style="color:green"><b>Admin</b> @Session["NomCompte"]</b>

                                            }
                                        }*@
                                    </h3>
                                    
                                </div>

                            </div>
                        </div>
                        <div class="col-4">

                        </div>
                    </div>


                    <div class="row mb-5">
                        <div class="col">
                            <div class="card card-profile text-center">
                                <span class="mb-1 text-primary"><i class="icon-home"></i></span>
                                <h3 class="mb-0">Role:</h3>
                                <p class="text-muted px-4">Admin</p>
                            </div>
                        </div>
                        @*<div class="col">
                            <div class="card card-profile text-center">
                                <span class="mb-1 text-warning"><i class="icon-globe-alt"></i></span>
                                <h3 class="mb-0">Filière</h3>
                                <p class="text-muted">3iAC</p>
                            </div>
                        </div>*@
                        <div class="col-12 text-center">
                            <button onclick="AfficheModalImage()" class="btn btn-danger px-5">Changer ma photo</button>
                        </div>
                    </div>

                    <h4>Contact</h4>

                    <ul class="card-profile__info">
                        <li class="mb-1"><strong class="text-dark mr-4">Tel:</strong> <span>656446641</span></li>
                        <li><strong class="text-dark mr-4">Email:</strong> <span>fulthonn@gmail.com</span></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>





<script>

     var AfficheModalImage = function () {

         $("#modalProfilImage").modal("show");

            //$("#table").ajax.reload();

     }

      var previewimg = function (event) {
            var result = document.getElementById("profilImageModoal");
            result.src = URL.createObjectURL(event.target.files[0]);
      }


         var showInPopup = function (url, title) {
            $.ajax({
                type: "GET",
                url: url,
                success: function (res) {
                    $("#form-modal .modal-body").html(res);
                    $("#form-modal .modal-title").html(title);
                    $("#form-modal").modal("show");

                    GetList();

                }
            })
        };
</script>