HospitalManagementSystem/Controllers/CaisseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalManagementSystem.Models;

namespace HospitalManagementSystem.Controllers
{
    [Authorize]
    public class CaisseController : Controller
    {
        private Clinique_dbEntities db = new Clinique_dbEntities();

        // GET: Caisse
        public async Task<ActionResult> Index()
        {
            var fiches = db.Fiches.Include(f => f.Configuration).Include(f => f.LibelleActe).Include(f => f.Patient).Include(f => f.Personnel);
            return View(await fiches.ToListAsync());
        }

        public ActionResult GetAll()
        {
            var fiches = db.Fiches.Where(x => x.Date.Day.Equals(DateTime.Now.Day)

            && x.Date.Year.Equals(DateTime.Now.Year) && x.Date.Month.Equals(DateTime.Now.Month)).Include(f => f.Configuration).Include(f => f.LibelleActe).Include(f => f.Patient).Include(f => f.Personnel);
            return PartialView("GetAll", fiches.ToList());
        }



        // GET: Caisse/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fiche fiche = await db.Fiches.FindAsync(id);
            if (fiche == null)
            {
                return HttpNotFound();
            }
            return View(fiche);
        }

        // GET: Caisse/Create
        public ActionResult Create()
        {
            ViewBag.Raison = new SelectList(db.Configurations, "IdConfiguration", "Libelle");
            ViewBag.CodeExamen = new SelectList(db.LibelleActes, "Code", "Libelle");
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom");
            ViewBag.CodeSecretaire = new SelectList(db.Personnels, "Code", "Nom");
            return View();
        }

        //paiement de la consultation
        public async Task<ActionResult> Payer(int? id)
        {
            Fiche fiche = await db.Fiches.FindAsync(id);
            if (fiche.Paiement == 0)
            {
                fiche.Paiement = 1;
            }
            //else
            //{
            //    fiche.Paiement = 0;
            //}
           
            db.Entry(fiche).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // POST: Caisse/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CodePatient,CodeSecretaire,Date,Paiement,Raison,CodeExamen")] Fiche fiche)
        {
            if (ModelState.IsValid)
            {
                db.Fiches.Add(fiche);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Raison = new SelectList(db.Configurations, "IdConfiguration", "Libelle", fiche.Raison);
            ViewBag.CodeExamen = new SelectList(db.LibelleActes, "Code", "Libelle", fiche.CodeExamen);
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom", fiche.CodePatient);
            ViewBag.CodeSecretaire = new SelectList(db.Personnels, "Code", "Nom", fiche.CodeSecretaire);
            return View(fiche);
        }

        // GET: Caisse/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fiche fiche = await db.Fiches.FindAsync(id);
            if (fiche == null)
            {
                return HttpNotFound();
            }
            ViewBag.Raison = new SelectList(db.Configurations, "IdConfiguration", "Libelle", fiche.Raison);
            ViewBag.CodeExamen = new SelectList(db.LibelleActes, "Code", "Libelle", fiche.CodeExamen);
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom", fiche.CodePatient);
            ViewBag.CodeSecretaire = new SelectList(db.Personnels, "Code", "Nom", fiche.CodeSecretaire);
            return View(fiche);
        }

        // POST: Caisse/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CodePatient,CodeSecretaire,Date,Paiement,Raison,CodeExamen")] Fiche fiche)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fiche).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Raison = new SelectList(db.Configurations, "IdConfiguration", "Libelle", fiche.Raison);
            ViewBag.CodeExamen = new SelectList(db.LibelleActes, "Code", "Libelle", fiche.CodeExamen);
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom", fiche.CodePatient);
            ViewBag.CodeSecretaire = new SelectList(db.Personnels, "Code", "Nom", fiche.CodeSecretaire);
            return View(fiche);
        }

        // GET: Caisse/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fiche fiche = await db.Fiches.FindAsync(id);
            if (fiche == null)
            {
                return HttpNotFound();
            }
            return View(fiche);
        }

        // POST: Caisse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Fiche fiche = await db.Fiches.FindAsync(id);
            db.Fiches.Remove(fiche);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalManagementSystem/Views/Caisse/Create.cshtml
@model HospitalManagementSystem.Models.Fiche

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout_Caisse.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fiche</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CodePatient, "CodePatient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodePatient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodePatient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodeSecretaire, "CodeSecretaire", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodeSecretaire", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodeSecretaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paiement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Paiement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Paiement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raison, "Raison", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Raison", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Raison, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodeExamen, "CodeExamen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodeExamen", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodeExamen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalManagementSystem/Views/Caisse/Delete.cshtml
@model HospitalManagementSystem.Models.Fiche

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout_Caisse.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Fiche</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paiement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paiement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LibelleActe.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LibelleActe.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospitalManagementSystem/Views/Caisse/Details.cshtml
@model HospitalManagementSystem.Models.Fiche

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout_Caisse.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Fiche</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Paiement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paiement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LibelleActe.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LibelleActe.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalManagementSystem/Views/Caisse/Edit.cshtml
@model HospitalManagementSystem.Models.Fiche

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout_Caisse.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fiche</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CodePatient, "CodePatient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodePatient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodePatient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodeSecretaire, "CodeSecretaire", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodeSecretaire", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodeSecretaire, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paiement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Paiement, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Paiement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raison, "Raison", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Raison", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Raison, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodeExamen, "CodeExamen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodeExamen", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodeExamen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalManagementSystem/Views/Caisse/GetAll.cshtml
@model IEnumerable<HospitalManagementSystem.Models.Fiche>

@*<p>
    @Html.ActionLink("Nouveau", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
           Patient
        </th>
        <th>
            Médecin
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        @*<th>
            Statut
        </th>*@
        <th>
            Raison
        </th>
        <th>
            Examen
        </th>

        <th>Action</th>
    </tr>

    @foreach (var item in Model)
    {
        if (item.Paiement == 0)
        {
            <tr style="color:red">
                <td>
                    @Html.DisplayFor(modelItem => item.Patient.NomComplet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Personnel.NomComplet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Paiement)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Configuration.Libelle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LibelleActe.Libelle)
                </td>

                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                    <a href="#" class="btn mb-1 btn-primary btn-xm" onclick="confirmeactiver(@item.Id)"><i>Valider</i></a>
                </td>
            </tr>
        }
        else
        {
            <tr style="color:green">
                <td>
                    @Html.DisplayFor(modelItem => item.Patient.NomComplet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Personnel.NomComplet)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Paiement)
                </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Configuration.Libelle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LibelleActe.Libelle)
                </td>

                <td>
                    @*@html.actionlink("edit", "edit", new { id = item.id }) |
                        @html.actionlink("details", "details", new { id = item.id }) |
                        @html.actionlink("delete", "delete", new { id = item.id })|*@
                    <a href="#"  class="btn mb-1 btn-primary btn-xm disabled" onclick="confirmeactiver(@item.Id)"><i>Valider</i></a>
                </td>
            </tr>
        }

    }

</table>

HospitalManagementSystem/Views/Caisse/Index.cshtml
@model IEnumerable<HospitalManagementSystem.Models.Fiche>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Caisse.cshtml";
}


<div class="row">
    <!-- begin col-6 -->
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#default-tab-1" data-toggle="tab" style="background-color:#00ACAC">Frais consultation</a></li>
            <li class=""><a href="#default-tab-2" data-toggle="tab" style="background-color:#348FE2" >Frais Examen</a></li>
            <li class=""><a href="#default-tab-3" data-toggle="tab">Frais divers</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade active in" id="default-tab-1">
                <div>
                    <div col-md-2>

                    </div>
                    <div col-md-8 id="dataContainer">
                        @{ Html.RenderAction("GetAll", "Caisse");}
                    </div>
                    <div col-md-2>

                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="default-tab-2">
                @* Rendre la vue frais examen en attente de validation *@
                <div>
                    <div col-md-2>

                    </div>
                    <div col-md-8 id="dataContainerFraisExam">
                        @{ Html.RenderAction("GetListFraisExamen", "Consultation");}
                    </div>
                    <div col-md-2>

                    </div>
                </div>
               
            </div>
            <div class="tab-pane fade" id="default-tab-3">
                @* Rendre la vue de la liste des rendez-vous *@
                @*@{ Html.RenderAction("GetAll", "Pharm_Equivalent");}*@
            </div>
        </div>

    </div>
    <!-- end col-6 -->
</div>



@* Modal de validation de frais d'examen *@
<!-- Modal -->
<div class="modal fade" id="ModalConfirFraisExamen">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Validation du paiement de l'éxamen</h4>
            </div>
            <div class="modal-body" id="myModalBodyFraisExamen">
                Voulez-vous vraiment valider cet examen ?
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn mb-1 btn-warning btn-xs" data-dismiss="modal">Close</a>
                <a href="#" onclick="validerFraisExamen()" class="btn mb-1 btn-success btn-xs ">Oui</a>
            </div>
        </div>
    </div>
</div>


@* Modal de validation de frais de consultation *@
<!-- Modal -->
<div class="modal fade" id="mymodalactiver">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Validation de consultation</h4>
            </div>
            <div class="modal-body" id="myModalBody">
                <b style="color:orangered"> Voulez-vous vraiment valider ce paiement ?</b>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn mb-1 btn-warning btn-xs" data-dismiss="modal">Close</a>
                <a href="#" onclick="activaterAccount()" class="btn mb-1 btn-success btn-xs ">Oui</a>
            </div>
        </div>
    </div>
</div>




<input type="hidden" id="hiddenAccountId" />

<input type="hidden" id="hiddenFraisExam" />

<!-- Modal -->
<div class="modal fade" id="mymodaldesactiver">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Modal Dialog</h4>
            </div>
            <div class="modal-body" id="myModalBody2">
                Voulez-vous vraiment valider ce paiement ?
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Close</a>
                <a href="#" onclick="desactivaterAccount()" class="btn mb-1 btn-primary btn-xs ">Oui</a>
            </div>
        </div>
    </div>
</div>

<script>
    //confirme définitivement l'activation
         var activaterAccount = function () {

            //$("#loaderVid").show();
            var donnee = $("#hiddenAccountId").val();
            $.ajax({
                type: "POST",
                url: "/Caisse/Payer",
                data: { id: donnee },
                success: function () {
                    //$("#loaderVid").hide();
                    $("#mymodalactiver").modal("hide");
                    //$("#table").ajax.reload();
                    GetList();

                },

            });

        }

    //confirme définitivement la valisation de frais d'examen
         var validerFraisExamen = function () {

            //$("#loaderVid").show();
            var donnee = $("#hiddenFraisExam").val();
            $.ajax({
                type: "POST",
                url: "/Consultation/Payer",
                data: { id: donnee },
                success: function () {
                    //$("#loaderVid").hide();
                    $("#mymodalactiver").modal("hide");
                    //$("#table").ajax.reload();
                    GetList();

                },

            });

        }


     //rafraichir la list
         function GetList() {
             $.ajax({
                    url: '@Url.Action("GetAll", "Caisse")'

             }).done(function(result) {
                    $('#dataContainer').html(result);
                     //$('#table').DataTable()
                    console.log(result)
             }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                     console.log(textStatus)
                     console.log(errorThrown)
                     alert("Something Went Wrong, Try Later");
             });
        }


    //rafraichir la list de paiement des examens
         function GetListExam() {
             $.ajax({
                    url: '@Url.Action("GetListFraisExamen", "Consultation")'

             }).done(function(result) {
                    $('#dataContainerFraisExam').html(result);
                     //$('#table').DataTable()
                    console.log(result)
             }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                     console.log(textStatus)
                     console.log(errorThrown)
                     alert("Something Went Wrong, Try Later");
             });
        }

    //affiche le modal en appelant à confirmer l'activation
    var confirmeactiver = function (id) {
        $("#hiddenAccountId").val(id);
        $("#mymodalactiver").modal("show");


    }
    //affiche le modal en invitant à confirmer la désactivation
    var confirmedesactiver = function (id) {
        $("#hiddenAccountId").val(id);
        $("#mymodaldesactiver").modal("show");


    }

     var ModalConfirFraisExamen = function (id) {
        $("#hiddenFraisExam").val(id);
        $("#ModalConfirFraisExamen").modal("show");


    }


</script>