HospitalManagementSystem/Models/Patient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Fiches = new HashSet<Fiche>();
            this.Parametres = new HashSet<Parametre>();
            this.RendezVous = new HashSet<RendezVou>();
        }
    
        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fiche> Fiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parametre> Parametres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RendezVou> RendezVous { get; set; }
    }
}

HospitalManagementSystem/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalManagementSystem.Models;

namespace HospitalManagementSystem.Controllers
{
    [Authorize]
    public class PatientController : Controller
    {
        private Clinique_dbEntities db = new Clinique_dbEntities();

        // GET: Patient
        public async Task<ActionResult> Index()
        {
            return View(await db.Patients.ToListAsync());
        }

        //Get all
        
        public ActionResult GetAll()
        {
            //var ficheDuJOur = db.Fiches.Where(x => x.Date.Day.Equals(DateTime.Now.Day)
            //  && x.Date.Year.Equals(DateTime.Now.Year) && x.Date.Month.Equals(DateTime.Now.Month));

            return PartialView(db.Patients.ToList());
        }

        // GET: Patient/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = await db.Patients.FindAsync(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

       

        // GET: Patient/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patient/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Code,Nom,Prenom,NomComplet,DateNaissance,Adresse,Telephone,Email,Sexe,AntecedentFamiliaux,AntecedentChirucauxPersonnel,AntecedentMedicauxPersonnel,Allergie,SituationMatrimogniale")] Patient patient)
        {
            int cod = 0;
            var patients = db.Patients;

            List<string> listCode = new List<string>();
            List<int> listCodeInt = new List<int>(); ;
            
            
            foreach(var i in patients)
            {
                listCode.Add(i.Code);
            }

            foreach(var c in listCode)
            {
                int co=0;
                bool a = int.TryParse(c,out co)?true:false;
                if (a==true)
                {
                    
                    listCodeInt.Add(co);
                }
            }

            if (listCodeInt == null)
            {
                cod = 0;
            }
            if(listCodeInt!=null)
            {
                cod = listCodeInt.Max() + 1;
            }



            patient.NomComplet = patient.Nom + " " + patient.Prenom;
            patient.Code = cod.ToString();

           

            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: Patient/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = await db.Patients.FindAsync(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patient/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Code,Nom,Prenom,NomComplet,DateNaissance,Adresse,Telephone,Email,Sexe,AntecedentFamiliaux,AntecedentChirucauxPersonnel,AntecedentMedicauxPersonnel,Allergie,SituationMatrimogniale")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                db.Entry(patient).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: Patient/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = await db.Patients.FindAsync(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Patient patient = await db.Patients.FindAsync(id);
            db.Patients.Remove(patient);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalManagementSystem/Views/Patient/Create.cshtml
@model HospitalManagementSystem.Models.Patient

@{
    ViewBag.Title = "Create";
  Layout = "~/Views/Shared/_Layout_Secretaire.cshtml";
}

<div div class="col-md-3">

</div>

<div class="row">

    <!-- begin col-6 -->
    <div class="col-md-6">
        <!-- begin panel -->
        <div class="panel panel-inverse" data-sortable-id="form-stuff-3">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Nouveau patient</h4>
            </div>
            <div class="panel-body">
                <form action="~/Patient/Create" method="POST">
                    <fieldset>
                        @Html.AntiForgeryToken()
                        <form class="form-horizontal">
                            <div class="form-horizontal">
                                <hr />
                                @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                    </div>
                                </div>*@

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                @*<div class="form-group">
                                    @Html.LabelFor(model => model.NomComplet,"Nom complet", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.NomComplet, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.NomComplet, "", new { @class = "text-danger" })
                                    </div>
                                </div>*@

                                <div class="form-group">
                                    @Html.LabelFor(model => model.DateNaissance,"Naissance", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.DateNaissance, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DateNaissance, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Telephone,"Phone", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @*@Html.EditorFor(model => model.Sexe, new { htmlAttributes = new { @class = "form-control" } })*@

                                        @Html.DropDownList("Sexe", new List<SelectListItem>
                                            {
                                               new SelectListItem{ Text="Homme", Value = "0" },
                                               new SelectListItem{ Text="Femme", Value = "1" },
                                               
                                            }, "Sexe", new { @class = "form-control"  })
                                        @Html.ValidationMessageFor(model => model.Sexe, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.AntecedentFamiliaux,"Ant. Fam.", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.AntecedentFamiliaux, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.AntecedentFamiliaux, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.AntecedentChirucauxPersonnel,"Ant. Chir. Per.", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.AntecedentChirucauxPersonnel, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.AntecedentChirucauxPersonnel, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.AntecedentMedicauxPersonnel,"Ant. Med. Per.", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.AntecedentMedicauxPersonnel, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.AntecedentMedicauxPersonnel, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Allergie, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Allergie, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Allergie, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.SituationMatrimogniale,"Sit Matri.", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.SituationMatrimogniale, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.SituationMatrimogniale, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Enregistrer" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        </form>
                    </fieldset>
                </form>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-6 -->
    <div div class="col-md-3">

    </div>
</div>




<div>
    @Html.ActionLink("Retour", "Index")
</div>

@*@section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }*@

HospitalManagementSystem/Views/Patient/Delete.cshtml
@model HospitalManagementSystem.Models.Patient

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout_Secretaire.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomComplet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomComplet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentFamiliaux)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentFamiliaux)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentChirucauxPersonnel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentChirucauxPersonnel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentMedicauxPersonnel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentMedicauxPersonnel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allergie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allergie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SituationMatrimogniale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SituationMatrimogniale)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospitalManagementSystem/Views/Patient/Details.cshtml
@model HospitalManagementSystem.Models.Patient

@{
    ViewBag.Title = "Details";
   Layout = "~/Views/Shared/_Layout_Secretaire.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomComplet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomComplet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentFamiliaux)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentFamiliaux)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentChirucauxPersonnel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentChirucauxPersonnel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentMedicauxPersonnel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentMedicauxPersonnel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allergie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allergie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SituationMatrimogniale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SituationMatrimogniale)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Code }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalManagementSystem/Views/Patient/DetailsP.cshtml
@model HospitalManagementSystem.Models.Patient

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomComplet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomComplet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentFamiliaux)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentFamiliaux)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentChirucauxPersonnel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentChirucauxPersonnel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AntecedentMedicauxPersonnel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AntecedentMedicauxPersonnel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Allergie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Allergie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SituationMatrimogniale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SituationMatrimogniale)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Code }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalManagementSystem/Views/Patient/Index.cshtml
@model IEnumerable<HospitalManagementSystem.Models.Patient>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Secretaire.cshtml";
}






<div>
    <div col-md-2>

    </div>
    <div col-md-8 id="dataContainer">
        @{ Html.RenderAction("GetAll", "Patient");}
    </div>
    <div col-md-2>

    </div>
</div>




<script>


    //affiche le modal d'enregistrement des paramètres
    var modalparametre = function () {

        $("#idmodalparametre").modal("show");


    }

    //affiche une vue dans un modal
    var showInPopup = function (url, title) {
        $.ajax({
            type: "GET",
            url: url,
            success: function (res) {
                $("#form-modal .modal-body").html(res);
                $("#form-modal .modal-title").html(title);
                $("#form-modal").modal("show");

                GetList();

            }
        })
    };

  
    
       

</script>