HospitalManagementSystem/Models/RendezVou.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendezVou
    {
        
    
        public virtual Configuration Configuration { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}

HospitalManagementSystem/Controllers/RendezVousController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalManagementSystem.Models;

namespace HospitalManagementSystem.Controllers
{
    [Authorize]
    public class RendezVousController : Controller
    {
        private Clinique_dbEntities db = new Clinique_dbEntities();

        // GET: RendezVous
        public async Task<ActionResult> Index()
        {
            var rendezVous = db.RendezVous.Where(x => x.Date.Day.Equals(DateTime.Now.Day)
           && x.Date.Year.Equals(DateTime.Now.Year) && x.Date.Month.Equals(DateTime.Now.Month)).Include(r => r.Configuration).Include(r => r.Patient).Include(r => r.Personnel);
            return View(await rendezVous.ToListAsync());


            // var rendezVous = db.RendezVous.Include(r => r.Configuration).Include(r => r.Patient).Include(r => r.Personnel);
            // return View(await rendezVous.ToListAsync());


        }
        public ActionResult GetRdvDuJour()
        {
            var rendezVous = db.RendezVous.Where(x => x.Date.Day.Equals(DateTime.Now.Day)
            && x.Date.Year.Equals(DateTime.Now.Year) && x.Date.Month.Equals(DateTime.Now.Month)).Include(r => r.Configuration).Include(r => r.Patient).Include(r => r.Personnel);
            return PartialView(rendezVous.ToList());
        }
        
        // GET: RendezVous/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RendezVou rendezVou = await db.RendezVous.FindAsync(id);
            if (rendezVou == null)
            {
                return HttpNotFound();
            }
            return View(rendezVou);
        }

        // GET: RendezVous/Create
        public ActionResult Create()
        {
            ViewBag.IdType = new SelectList(db.Configurations.Where(x => x.Nature.Libelle.Equals("Type Rendez-vous")), "IdConfiguration", "Libelle");
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom");
            ViewBag.CodeMedecin = new SelectList(db.Personnels.Where(x => x.Configuration2.Libelle.Equals("Médecin")), "Code", "Nom");
            return View();
        }

        public ActionResult CreateRdvPartiel()
        {
            ViewBag.IdType = new SelectList(db.Configurations.Where(x=>x.Nature.Libelle.Equals("Type Rendez-vous")), "IdConfiguration", "Libelle");
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom");
            ViewBag.CodeMedecin = new SelectList(db.Personnels.Where(x=>x.Configuration2.Libelle.Equals("Médecin")), "Code", "Nom");
            return PartialView("CreateRdvPartiel");
        }

        // POST: RendezVous/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,IdType,CodePatient,CodeMedecin,Date,Statut,Raison")] RendezVou rendezVou)
        {
            rendezVou.IdType = 9;
            rendezVou.Statut = 0;
            if (ModelState.IsValid)
            {
                db.RendezVous.Add(rendezVou);
                await db.SaveChangesAsync();
                return RedirectToAction("Index","Consultation");
            }

            ViewBag.IdType = new SelectList(db.Configurations.Where(x => x.Nature.Libelle.Equals("Type Rendez-vous")), "IdConfiguration", "Libelle", rendezVou.IdType);
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom", rendezVou.CodePatient);
            ViewBag.CodeMedecin = new SelectList(db.Personnels.Where(x => x.Configuration2.Libelle.Equals("Médecin")), "Code", "Nom", rendezVou.CodeMedecin);
            return View(rendezVou);
        }

        // GET: RendezVous/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RendezVou rendezVou = await db.RendezVous.FindAsync(id);
            if (rendezVou == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdType = new SelectList(db.Configurations, "IdConfiguration", "Libelle", rendezVou.IdType);
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom", rendezVou.CodePatient);
            ViewBag.CodeMedecin = new SelectList(db.Personnels, "Code", "Nom", rendezVou.CodeMedecin);
            return View(rendezVou);
        }

        // POST: RendezVous/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,IdType,CodePatient,CodeMedecin,Date,Statut,Raison")] RendezVou rendezVou)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rendezVou).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdType = new SelectList(db.Configurations, "IdConfiguration", "Libelle", rendezVou.IdType);
            ViewBag.CodePatient = new SelectList(db.Patients, "Code", "Nom", rendezVou.CodePatient);
            ViewBag.CodeMedecin = new SelectList(db.Personnels, "Code", "Nom", rendezVou.CodeMedecin);
            return View(rendezVou);
        }

        // GET: RendezVous/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RendezVou rendezVou = await db.RendezVous.FindAsync(id);
            if (rendezVou == null)
            {
                return HttpNotFound();
            }
            return View(rendezVou);
        }

        // POST: RendezVous/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            RendezVou rendezVou = await db.RendezVous.FindAsync(id);
            db.RendezVous.Remove(rendezVou);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalManagementSystem/Views/RendezVous/Create.cshtml
@model HospitalManagementSystem.Models.RendezVou

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RendezVou</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdType, "IdType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodePatient, "CodePatient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodePatient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodePatient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodeMedecin, "CodeMedecin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodeMedecin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodeMedecin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raison, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Raison, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Raison, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalManagementSystem/Views/RendezVous/CreateRdvPartiel.cshtml
@model HospitalManagementSystem.Models.RendezVou


@using (Html.BeginForm("Create","RendezVous",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdType, "IdType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdType, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <input type="hidden" name="CodePatient" id="CodePatientt" />
        @*<div class="form-group">
            @Html.LabelFor(model => model.CodePatient, "CodePatient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodePatient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodePatient, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <input type="hidden" name="CodeMedecin" value="@Session["Code"]" />
        @*<div class="form-group">
            @Html.LabelFor(model => model.CodeMedecin, "CodeMedecin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodeMedecin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodeMedecin, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Raison, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Raison, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Raison, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-danger btn-md btn-rounded" data-dismiss="modal">Annuler</button>
                <input type="submit" value="Enregistrer" class="btn btn-success btn-md btn-rounded" />
            </div>
        </div>
    </div>
}

<script>
    var initRdvPatient = function (Code) {
        $("#CodePatientt").val(Code);


    }


</script>

HospitalManagementSystem/Views/RendezVous/Delete.cshtml
@model HospitalManagementSystem.Models.RendezVou

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RendezVou</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raison)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Raison)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospitalManagementSystem/Views/RendezVous/Details.cshtml
@model HospitalManagementSystem.Models.RendezVou

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>RendezVou</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raison)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Raison)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Configuration.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Configuration.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalManagementSystem/Views/RendezVous/Edit.cshtml
@model HospitalManagementSystem.Models.RendezVou

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RendezVou</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IdType, "IdType", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdType", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodePatient, "CodePatient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodePatient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodePatient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodeMedecin, "CodeMedecin", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CodeMedecin", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CodeMedecin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Raison, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Raison, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Raison, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalManagementSystem/Views/RendezVous/GetRdvDuJour.cshtml
@model IEnumerable<HospitalManagementSystem.Models.RendezVou>

<table  class="table table-striped table-bordered nowrap" width="100%">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
           Patient
        </th>
        <th>
           Medecin
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Statut)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Raison)
        </th>
        <th>
           Type
        </th>

        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Patient.NomComplet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Personnel.NomComplet)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Statut)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Raison)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Configuration.Libelle)
        </td>
        
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
            @Html.ActionLink("Supprim", "Delete", new { id = item.Id, @class="btn mb-1 btn-warning btn-xs" })
            <button id="modalActivate" onclick="initpatient(@item.Id,'@item.CodeMedecin')" type="button" class="btn mb-1 btn-primary btn-xs" data-toggle="modal" data-target="#@item.Id">
                    Cons
                </button>
            <button onclick="setExameValues('@item.CodePatient','@item.CodeMedecin')" type="button" class="btn mb-1 btn-warning btn-xs" data-toggle="modal" data-target="#prescrirExamen">
                examen
            </button>

            <button onclick="setExameValues('@item.CodePatient','@item.CodeMedecin')" type="button" class="btn mb-1 btn-success btn-xs" data-toggle="modal" data-target="#PresMedocApresCons">
                Médoc
            </button>

            <button onclick="initRdvPatient('@item.CodePatient')" type="button" class="btn mb-1 btn-primary btn-xs" data-toggle="modal" data-target="#ModalRdv">
                RDV
            </button>
        </td>
    </tr>
}

</table>

HospitalManagementSystem/Views/RendezVous/Index.cshtml
@model IEnumerable<HospitalManagementSystem.Models.RendezVou>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<p>
    @Html.ActionLink("Nouveau", "Create")
</p>
<table class="table">
    <tr>
        <th>
           Patient
        </th>
        <th>
           Medecin
        </th>
        <th>
            Date
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Statut)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Raison)
        </th>
        <th>
            Type RDV
        </th>

        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Patient.Nom)
            @Html.DisplayFor(modelItem => item.Patient.Prenom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Personnel.NomComplet)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Statut)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Raison)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Configuration.Libelle)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Supp", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>